### ISSUE TITLE
GAME_MODS_IDS_LIST does not add mods

### ISSUE THREAD

**Issue by hafometh88** [acemod/docker-reforger#24]
**Describe the bug**
Populate the variable GAME_MODS_IDS_LIST with mod IDs and after recreating the container, mods are not added to the server

**To Reproduce**
My docker-compose.yml

---
version: '3.8'
services:
  arma-reforger:
    image: ghcr.io/acemod/arma-reforger:edge
    platform: linux/amd64
    container_name: arma-reforger
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
    volumes:
      - /opt/reforger/configs:/reforger/Configs
      - /opt/reforger/profile:/home/profile
      - /opt/reforger/workshop:/reforger/workshop
    environment:
      - SERVER_PUBLIC_ADDRESS=foo
      - GAME_NAME=foo
      - SERVER_A2S_ADDRESS=0.0.0.0
      - SERVER_A2S_PORT=17777
      - GAME_PASSWORD_ADMIN=foo
      - GAME_MAX_PLAYERS=40
      - GAME_PROPS_DISABLE_THIRD_PERSON=true
      - ARMA_MAX_FPS=60
      - GAME_MODS_IDS_LIST=5994AD5A9F33BE57,5ED8BE1DDFEFBE4C,5D071A427403AB2C

**Comment by hafometh88** [comment]
Here are all logs from the container

[console.log](https://github.com/acemod/docker-reforger/files/13431839/console.log)
[error.log](https://github.com/acemod/docker-reforger/files/13431848/error.log)
[script.log](https://github.com/acemod/docker-reforger/files/13431849/script.log)

**Comment by sdsznsk** [comment]
I think I got the cause, working on a fix

**Comment by sdsznsk** [comment]
Actually I though the cause was something else ( #26 ) but rather it's the fact that support for mods was introduced after edge->latest switch from #22 , so it's not present in `edge` tag. 

Switch to `image: ghcr.io/acemod/arma-reforger:latest` will solve the issue.

**Comment by hafometh88** [comment]
I totally missed that, thank you! I used the docker-compose.yml template in the project, so I did not even look at the image tag properly :) Now I am just patiently waiting for #26 to be approved.
