### ISSUE TITLE
AssertionError: 5994AD5A9F33BE57=1.0.65 mod version does not match the pattern

### ISSUE THREAD

**Issue by hafometh88** [acemod/docker-reforger#28]
**Describe the bug**
When specifying mod version, the server does not want to start with the error in the headline
**To Reproduce**
1. Add a list of mods to GAME_MODS_IDS_LIST
2. Update the stack
3. RIP

**Expected behavior**
The server starts with specified mods and specified versions of the mods

**Screenshots / Output**

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1700160359
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.37 (14649778 / 3996621701)
 Update state (0x61) downloading, progress: 1.36 (54213048 / 3996621701)
 Update state (0x61) downloading, progress: 2.54 (101398548 / 3996621701)
 Update state (0x61) downloading, progress: 3.61 (144390164 / 3996621701)
 Update state (0x61) downloading, progress: 4.65 (185854924 / 3996621701)
 Update state (0x61) downloading, progress: 5.83 (232896820 / 3996621701)
 Update state (0x61) downloading, progress: 7.20 (287694691 / 3996621701)
 Update state (0x61) downloading, progress: 8.88 (354846079 / 3996621701)
 Update state (0x61) downloading, progress: 10.80 (431660218 / 3996621701)
 Update state (0x61) downloading, progress: 12.85 (513527399 / 3996621701)
 Update state (0x61) downloading, progress: 15.18 (606497023 / 3996621701)
 Update state (0x61) downloading, progress: 17.44 (696924229 / 3996621701)
 Update state (0x61) downloading, progress: 19.84 (793108603 / 3996621701)
 Update state (0x61) downloading, progress: 22.74 (908924472 / 3996621701)
 Update state (0x61) downloading, progress: 25.69 (1026540461 / 3996621701)
 Update state (0x61) downloading, progress: 28.66 (1145610811 / 3996621701)
 Update state (0x61) downloading, progress: 31.63 (1263968514 / 3996621701)
 Update state (0x61) downloading, progress: 34.66 (1385139120 / 3996621701)
 Update state (0x61) downloading, progress: 37.79 (1510209665 / 3996621701)
 Update state (0x61) downloading, progress: 41.40 (1654648809 / 3996621701)
 Update state (0x61) downloading, progress: 44.76 (1788965624 / 3996621701)
 Update state (0x61) downloading, progress: 48.52 (1939268573 / 3996621701)
 Update state (0x61) downloading, progress: 51.61 (2062525107 / 3996621701)
 Update state (0x61) downloading, progress: 54.83 (2191229365 / 3996621701)
 Update state (0x61) downloading, progress: 58.13 (2323249524 / 3996621701)
 Update state (0x61) downloading, progress: 62.08 (2481138863 / 3996621701)
 Update state (0x61) downloading, progress: 65.64 (2623334950 / 3996621701)
 Update state (0x61) downloading, progress: 69.58 (2780710375 / 3996621701)
 Update state (0x61) downloading, progress: 72.91 (2913879527 / 3996621701)
 Update state (0x61) downloading, progress: 76.00 (3037611495 / 3996621701)
 Update state (0x61) downloading, progress: 79.34 (3170904280 / 3996621701)
 Update state (0x61) downloading, progress: 82.72 (3306133636 / 3996621701)
 Update state (0x61) downloading, progress: 85.90 (3433025908 / 3996621701)
 Update state (0x61) downloading, progress: 88.50 (3536834932 / 3996621701)
 Update state (0x61) downloading, progress: 91.12 (3641705689 / 3996621701)
 Update state (0x61) downloading, progress: 94.07 (3759633927 / 3996621701)
 Update state (0x61) downloading, progress: 96.33 (3849872746 / 3996621701)
 Update state (0x61) downloading, progress: 98.54 (3938246664 / 3996621701)
 Update state (0x61) downloading, progress: 99.95 (3994524549 / 3996621701)
 Update state (0x81) verifying update, progress: 10.13 (404910825 / 3996621701)
 Update state (0x81) verifying update, progress: 21.69 (866933587 / 3996621701)
 Update state (0x81) verifying update, progress: 32.97 (1317821267 / 3996621701)
 Update state (0x81) verifying update, progress: 44.18 (1765689963 / 3996621701)
 Update state (0x81) verifying update, progress: 55.35 (2212236843 / 3996621701)
 Update state (0x81) verifying update, progress: 66.90 (2673855483 / 3996621701)
 Update state (0x81) verifying update, progress: 78.33 (3130442490 / 3996621701)
 Update state (0x81) verifying update, progress: 89.81 (3589211885 / 3996621701)
Success! App '1874900' fully installed.
Traceback (most recent call last):
  File "/launch.py", line 138, in <module>
    assert reg.match(
AssertionError: 5994AD5A9F33BE57=1.0.65 mod version does not match the pattern

**Additional context**
My docker-compose.yml

---
version: '3.8'
services:
  arma-reforger:
    image: ghcr.io/acemod/arma-reforger:latest
    platform: linux/amd64
    container_name: arma-reforger
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
    volumes:
      - /opt/reforger/configs:/reforger/Configs
      - /opt/reforger/profile:/home/profile
      - /opt/reforger/workshop:/reforger/workshop
    environment:
      - SERVER_PUBLIC_ADDRESS=foo
      - GAME_NAME=foo
      - SERVER_A2S_ADDRESS=0.0.0.0
      - SERVER_A2S_PORT=17777
      - GAME_PASSWORD_ADMIN=foo
      - GAME_MAX_PLAYERS=40
      - GAME_PROPS_DISABLE_THIRD_PERSON=true
      - ARMA_MAX_FPS=60
      - GAME_MODS_IDS_LIST=5EDF4DB9362BF543,5D071A427403AB2C,5994AD5A9F33BE57=1.0.65

The problematic mod is [GameMasterFX](https://reforger.armaplatform.com/workshop/5994AD5A9F33BE57-GameMasterFX)

**Comment by sdsznsk** [comment]
Thanks for catching all my messy bugs 🤕
